### ISSUE TITLE
Mnemonic generation private key

### ISSUE THREAD

**Issue by developerjet** [anquii/BIP44#1]
Hello, how to generate the corresponding private key and address through mnemonic words?

**Comment by anquii** [comment]
> Hello, how to generate the corresponding private key and address through mnemonic words?

Hi @developerjet, please have a look at [this](https://github.com/anquii/BIP44/blob/main/README.md#usage) part of the [README](https://github.com/anquii/BIP44/blob/main/README.md). It details how you can use `AccountProvider` to get an indexed `Account` derivated from a seed. (If needed, you can use [BIP39](https://github.com/anquii/BIP39) to construct a mnemonic and derivate a seed from it.) You can then access the account's private key through its `serializedKey` property. To encode the key as a _base58Check_ ([example](https://github.com/anquii/BIP44/blob/7dfe4e5030a7e4d19750833331b223c8747a0e56/Tests/BIP44Tests/AccountProviderTests.swift#L22)), you can use `SerializedKeyCoder` from [BIP32](https://github.com/anquii/BIP32).

For addresses (derivated from an account), you can use `AddressProvider`. By using its `addressAndPrivateKey` function with an index as input, you can get both an address and its corresponding private key. To encode this key in a _WIF-compressed_ format ([example](https://github.com/anquii/BIP44/blob/7dfe4e5030a7e4d19750833331b223c8747a0e56/Tests/BIP44Tests/AddressProviderTests.swift#L41)), you can use `CompressedWIFKeyCoder` from [BIP32](https://github.com/anquii/BIP32).
