### ISSUE TITLE
cannot be resolved.

### ISSUE THREAD

**Issue by yspreen** [anquii/BIP44#2]
Failed to resolve dependencies Dependencies could not be resolved because 'bip44' depends on 'bip32' 1.1.2.
'bip32' 1.1.2 cannot be used because 'bip32' 1.1.2 depends on 'secp256k1.swift' 0.14.0 and no versions of 'secp256k1.swift' match the requirement 0.14.0.

**Comment by anquii** [comment]
> Failed to resolve dependencies Dependencies could not be resolved because 'bip44' depends on 'bip32' 1.1.2. 'bip32' 1.1.2 cannot be used because 'bip32' 1.1.2 depends on 'secp256k1.swift' 0.14.0 and no versions of 'secp256k1.swift' match the requirement 0.14.0.

Just checked and had no issues resolving the graph myself. You can see [here](https://github.com/GigaBitcoin/secp256k1.swift/releases/tag/0.14.0) that `secp256k1.swift` v0.14.0 does exist.

Can you pls try again, perhaps clearing your package cache first, or if that doesn't work, share a few details on your setup if it's anything out of the ordinary.
